version: "3.4"

services:
  elasticsearch1:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.15
    # volumes:
    #   - ./data:/usr/share/elasticsearch/data
    ports:
      - 19100:9100
      - 19200:9200
      - 19300:9300
    environment:
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=false
      - http.host=0.0.0.0
      - transport.host=0.0.0.0
      - discovery.type=single-node
      - http.cors.enabled=true
      - http.cors.allow-origin="*"

  # kibana:
  #   image: docker.elastic.co/kibana/kibana:7.3.0
  #   ports:
  #     - 15601:5601
  #   depends_on:
  #     - elasticsearch
